//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNotify.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1970-01-01")]
        public global::System.DateTime LastUpdate {
            get {
                return ((global::System.DateTime)(this["LastUpdate"]));
            }
            set {
                this["LastUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{""message"": ""success"", ""request"": {""latitude"": 45.473610000000001, ""passes"": 3, ""altitude"": 100, ""longitude"": -122.64931, ""datetime"": 1316763839}, ""response"": [{""duration"": 353, ""risetime"": 1316796673}, {""duration"": 611, ""risetime"": 1316802260}, {""duration"": 609, ""risetime"": 1316808023}]}")]
        public string LastUpdateData {
            get {
                return ((string)(this["LastUpdateData"]));
            }
            set {
                this["LastUpdateData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"Index\":0,\"PlaceName\":\"Portland\",\"Latitude\":45.47361,\"Longitude\":-122.649307,\"A" +
            "ltitude\":1200},{\"Index\":1,\"PlaceName\":\"New York\",\"Latitude\":40.25,\"Longitude\":-8" +
            "0.45,\"Altitude\":50}]")]
        public string Locations {
            get {
                return ((string)(this["Locations"]));
            }
            set {
                this["Locations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultLocation {
            get {
                return ((int)(this["DefaultLocation"]));
            }
            set {
                this["DefaultLocation"] = value;
            }
        }
    }
}
