#!/usr/bin/python
import gui.views
import gui.framework
import data.locations
import serial
import random

class OpenNotify:

  def __init__(self):
  
    self.app   = gui.framework.Application()
    self.state = gui.framework.ApplicationData()

    loc = data.locations.Location()
    loc.name = "Portland, OR"
    loc.latitude = 45.51200
    loc.longitude = -122.631007
    loc.altitude = 150.0
    self.state.location = loc

    self.view  = gui.views.MainWindow(self, self.state)
    self.app.main = self.view

    self.app.run()

  def blink(self, color):
    
    c = self.rgb2device(color)
    
    try:
      ser = serial.Serial('/dev/ttyACM0', 9600, timeout=0.1)
      
      print "c" + str(c)
      ser.write("c" + str(c))
      
      print "sent command"
      
      """
      for i in range(10):
        line  = ser.readline()
        if line != "":
          for c in line:
            print ord(c),
          
      """
      ser.close()
    except:
      print "No device"
    #print "recieve"

  def rgb2device(self, color):
    
    r = color[0] / 30
    g = color[1] / 30
    b = color[2] / 30
    
    c = r + (g<<4) + (b<<8)
    
    return c
    

if __name__ == "__main__":
    run = OpenNotify()
